### ISSUE TITLE
Extended Tag functionality broken on git master version from 2020.05.10?

### ISSUE THREAD

**Issue by iGadget** [keithgg/puddletag#473]
As per the comment of @miniworm, I'm creating a new issue for the problem below:

> If anyone is interrested in very latest puddletag (git master from 2020.05.10) you can find it as an appimage here (prepared by me):
> 
> https://gofile.io/d/4LQICt
> 
> Changelog can be found here:
> 
> [Commits between v1.2.0 and master](https://github.com/keithgg/puddletag/compare/v1.2.0...master)

First of, thank you SO much for the AppImage! Been running the 20200510 version and it's a real life saver. That said, I ran into this when trying to access the 'Extended Tags' functionality (CTRL+E):
```
Traceback (most recent call last):
  File "/tmp/.mount_puddleCbkEDH/usr/lib/python2.7/dist-packages/puddlestuff/mainwin/funcs.py", line 167, in extended_tags
    status['previewmode'], status=status)
  File "/tmp/.mount_puddleCbkEDH/usr/lib/python2.7/dist-packages/puddlestuff/helperwin.py", line 711, in __init__
    self._prevnext(row)
  File "/tmp/.mount_puddleCbkEDH/usr/lib/python2.7/dist-packages/puddlestuff/helperwin.py", line 980, in _prevnext
    self.loadFiles([self._files[row]])
  File "/tmp/.mount_puddleCbkEDH/usr/lib/python2.7/dist-packages/puddlestuff/helperwin.py", line 883, in loadFiles
    self._loadsingle(audio)
  File "/tmp/.mount_puddleCbkEDH/usr/lib/python2.7/dist-packages/puddlestuff/helperwin.py", line 939, in _loadsingle
    italics = tags.equal_fields()
AttributeError: 'Tag' object has no attribute 'equal_fields'
```
This is what's shown when I run the AppImage from the console. The program itself shows nothing when hitting CTRL+E. Any idea what's going on here? The extended tags function works fine on the previous puddletag-1.2.0.glibc2.15-x86_64.AppImage you posted earlier.

_Originally posted by @iGadget in https://github.com/keithgg/puddletag/issues/464#issuecomment-648986479_
